### PR TITLE
Comments: use proper WP

### PR DESCRIPTION
**Pull request by yoavf**
Use a iframe with a proper WP loaded single page, with a bunch of hacks around routing and urls.

### CODE REVIEW

**Comment by yoavf** [comment]
TODO: 

- [x] make sure the iframe url can't be loaded directly, and doesn't get indexed.
- [x] Decide and implement moderation rules
- [x] Test and possibly alter or disable comment/post notification emails

**Comment by akirk** [comment]
WIP Screenshot

**Comment by yoavf** [comment]
- Disabled follow buttons for now
- Only loading the comments when the editor loads. This doesn't feel optimal right now, but loading on page load when you have 20 iframes is way too slow.
- Added filtering by locale of the comments

**Comment by yoavf** [comment]
Replaced with #2

**Pull request closed without merging**
